### ISSUE TITLE
Ask teacher colleagues whether they believe knowledge of who is participating is impactful...

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#10]

**Comment by VictorChenLi** [comment]
just a informal small talking without mention the concept of baton, but given the context. if you got any feedback, you can simply just put here as comment

**Comment by ZT83** [comment]
Unfortunately, the answers I received were very mixed! It was equal opinions on both sides. Many teachers felt that knowledge of participants was essential, while others felt like that knowledge would influence others too much.

**Comment by VictorChenLi** [comment]
I will close this issue as we discussed at issue #8 
We probably will make this as a option, so teacher can decide whether they wanna students see it or not
