### ISSUE TITLE
Investigate research (e.g. Gender Bias) to support inclusion of both participation count AND selection count

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#20]
Gather both gender bias/racial bias information 

AND

research about how teachers perform WITH THE KNOWLEDGE OF THE BIAS (e.g. Do they change their behaviour?  Do they call on boys and girls more equally?)

https://www.questia.com/library/journal/1G1-19279162/you-guys-are-overreacting-teaching-prospective-teachers

**Comment by VictorChenLi** [comment]
@ZT83 If you can bring more feedback on this topic will help on whether we need gende/race as a profile information in our system

If we could have some information about it before end of next week will be great
