### ISSUE TITLE
Redesign for mobile orientation - Student Side

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#22]
- We need to redesign the visual layout, i.e. the screen size and icon sizes, and x/y axis of location based objects for mobile

- When participation is selected, participation wheel needs to collapse into itself, and be replaced by a central icon, with a newly created participation bubble
- When central icon is tapped, participation wheel needs to reopen, and participation bubble needs to be collapsed into middle

**Comment by VictorChenLi** [comment]
// for student menu
$("#menu-toggler").trigger("click");

// for student buddys
$(buddys).css({"transform": "translate3d(0px, 0px, 0px)"});
$(buddys).hide();
