### ISSUE TITLE
App Icon/Splash screen for Student and teacher side

### ISSUE THREAD

**Issue by VictorChenLi** [VictorChenLi/BatonMeteor#41]
Different Slogan and pic for student and teacher side

Teacher: Making teaching smarter
Student: ???

**Comment by ZT83** [comment]
Teacher/Student: Making discussions smarter.

**Comment by VictorChenLi** [comment]
![splash-xhdpi](https://cloud.githubusercontent.com/assets/6303030/16281418/5b9c8ade-3892-11e6-8ab0-ff51db363572.png)
