### ISSUE TITLE
Loading (post Meteor screen) after killing app WHILE LOGGED IN displays white screen for far too long or doesn't load at all

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#45]
APPLICATION: Teacher
Device: Android
SCREEN: Loading (post Meteor)
STEP: Rebooting app after killing when signed in as teacher
EXPECTING: To either have the app open to sign-in screen OR load to main menu, already logged in
ACTUAL: Tested 5 times.  

3 of 5 times (1st/3rd/4th = Meteor loading screen --> blank white screen displays for approx 20 to 40seconds --> app home screen loads

2 of 5 times (2nd/5th) = Meteor loading screen --> blank white screen that never loads anything else (waited for over 1 full minute before giving up)

*** ONLY RESOLUTION WAS TO REINSTALL ***

**Comment by VictorChenLi** [comment]
seems fixed, please check on as much device as possible
