### ISSUE TITLE
Can't Use Native Google Sign-In

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#66]
Device: Samsung Galaxy Note 5
OS: Android 6.0.1 (Marshmallow)
SCREEN: Login
STEP: When user taps on native Google sign in button
EXPECTING: To be able to sign in
ACTUAL: Taken to Google 404 page (see below) and unable to reclick Google sign in after returning to main login page, as it is "greyed out".

![screenshot_20160519-154156](https://cloud.githubusercontent.com/assets/15972054/15407500/29f93316-1dd9-11e6-87d1-93b53b4c0a52.png)

![20160519_155016](https://cloud.githubusercontent.com/assets/15972054/15407561/8081e3f4-1dd9-11e6-96b2-e4e5c6387449.png)

**Comment by VictorChenLi** [comment]
using a work around to always enable google login button, by adding 

```
Template.loginLayout.events({
	"click #at-google": function(event, template){
		AccountsTemplates.setDisabled(false);
	}
})
```
to login.js
