### ISSUE TITLE
Cursor visible in login fields

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#67]
APPLICATION: Teacher
Device: Galaxy Note 5
OS: Android 6.0.1 (Marshamallow)
SCREEN: Login
STEP: When user taps email field and password field
EXPECTING: To be able to enter text without seeing cursor
ACTUAL: Cursor visible

**Comment by VictorChenLi** [comment]
We will fix this through HIGHLIGHTING the field.
