### ISSUE TITLE
Text entered in login fields starts too much to the left

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#68]
APPLICATION: Teacher
Device: Samsung Galaxy Note 5
OS: Android 6.0.1 (Marshmallow)

When entering text into login fields, the actual text margin is set too far to the left.  This leaves the text looking "off" or "amateurish".

**Comment by VictorChenLi** [comment]
if you have a screen shot will be much better

**Comment by ZT83** [comment]
Not possible to capture via screenshot.  Will investigate taking "screen records" on my device.

**Comment by VictorChenLi** [comment]
1. Put in margin
2. Add in highlighting to selected text field
