### ISSUE TITLE
Classroom Info Won't Allow for "Back" Functionality

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#74]
APPLICATION: Teacher
Device: Samsung Galaxy Note 5
OS: Android 6.0.1 (Marshmallow)
SCREEN: Classroom Info
STEP: When user taps device "back" button
EXPECTING: For classroom info to close
ACTUAL: Classroom info stays open and only can be closed by tapping "x"

**Comment by VictorChenLi** [comment]
solved by close #78
