### ISSUE TITLE
Hitting device "back" button repeatedly leads to menu disappearing

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#75]
APPLICATION: Teacher
Device: Samsung Galaxy Note 5
OS: Android 6.0.1 (Marshmallow)
SCREEN: Profile/Work/Talk
STEP: When user taps device back button repeatedly
EXPECTING: For device to take user back out to device homescreen
ACTUAL: Baton menu refreshes constantly and then disappears

![tempfileforshare_2016-05-19-16-33-55](https://cloud.githubusercontent.com/assets/15972054/15408754/cf79c1ec-1ddf-11e6-903e-912af25117f1.jpg)

**Comment by VictorChenLi** [comment]
Handle the backpress button or action on Android

**Comment by VictorChenLi** [comment]
solved by add #78
