### ISSUE TITLE
Should students be able to see the "participation intent" (PI) of other students?

### ISSUE THREAD

**Issue by ZT83** [VictorChenLi/BatonMeteor#8]
1st thought = yes --> this is one of the core improvements over hand raising...and if the teacher has that information, why shouldn't the student.

2nd thought = no --> students may be influenced to participate in the same way as the majority, e.g. if they see that more people are challenging an idea than building, they might also go to challenge

NB: This is something we should test.  As well, this could be a customizable enhancement, where some teachers choose to allow students access to this info, and others do not, depending on the nature of their classroom.

**Comment by VictorChenLi** [comment]
I just create a knowledge label, so we can keep track all the issue that should keep as a knowledge ,which need invesigate or survey, for our future reference

**Comment by VictorChenLi** [comment]
I will close this issue for now, as we reach an agreement that we keep this information from student.
We will review this decision after we perform UX testing and actually on site beta testing
